import os
import json
import pandas as pd
from pathlib import Path

def generate_leaderboard():
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    reports_dir = os.path.join(base_dir, "reports")
    
    if not os.path.exists(reports_dir):
        print("No reports directory found.")
        return

    results = []
    
    for path in Path(reports_dir).rglob('*.json'):
        filename = path.name
        
        mode = "bar"
        stage_name = "Unknown"
        
        if filename == 'results_summary.json':
            stage_name = 'Stage 1 (Optuna - V1 Legacy)'
        elif filename.startswith('stage1_') and filename.endswith('_optuna_results.json'):
            mode = filename.replace('stage1_', '').replace('_optuna_results.json', '')
            stage_name = 'Stage 1 (Optuna)'
        elif filename.startswith('stage2_') and filename.endswith('_wfo_results.json'):
            mode = filename.replace('stage2_', '').replace('_wfo_results.json', '')
            stage_name = 'Stage 2 (WFO)'
        elif filename.startswith('stage3_') and filename.endswith('_holdout_results.json'):
            mode = filename.replace('stage3_', '').replace('_holdout_results.json', '')
            stage_name = 'Stage 3 (Holdout)'
        else:
            continue
            
        try:
            with open(path, 'r') as f:
                data = json.load(f)
                
            timeframe = path.parts[-2]
            strategy_name = path.parts[-3]
            
            if strategy_name.endswith("_OLD"):
                continue # Skip quarantined V1 folders
                
            score = 0.0
            metric_type = "Unknown"
            total_trades = 0
            
            if "metrics" in data: # Stage 1 format
                metrics = data.get("metrics", {})
                if mode == "forwardr" and "Profit_Factor_Forward" in metrics:
                    score = metrics.get("Profit_Factor_Forward", 0.0)
                    metric_type = "PF Forward"
                elif mode == "eratio" and "E_Ratio_Mean" in metrics:
                    score = metrics.get("E_Ratio_Mean", 0.0)
                    metric_type = "Mean E-Ratio"
                elif "Magnitude_Ratio" in metrics:
                    score = metrics.get("Magnitude_Ratio", 0.0)
                    metric_type = "Mag Ratio"
                elif "Profit_Factor_Total" in metrics:
                    score = metrics.get("Profit_Factor_Total", 0.0)
                    metric_type = "PF Total"
                elif "Profit_Factor_Long" in metrics:
                    score = metrics.get("Profit_Factor_Long", 0.0)
                    metric_type = "PF Long"
                elif "Profit_Factor_Short" in metrics:
                    score = metrics.get("Profit_Factor_Short", 0.0)
                    metric_type = "PF Short"
                    
                total_trades = metrics.get("Total_Trades", 0)
            else: # Stage 2/3 format
                score = data.get("profit_factor", 0.0)
                target = data.get("target", "Total")
                if mode == "forwardr":
                    metric_type = f"PF {target} (Forward)"
                elif mode == "eratio":
                    metric_type = f"PF {target} (E-Ratio Tuned)"
                else:
                    metric_type = f"PF {target}"
                total_trades = data.get("total_trades", 0)
            
            # Format the score to strictly avoid scientific notation (e.g. 1.23e-05)
            # We use 6 decimal places for precision on small forward returns
            formatted_score = f"{score:.6f}"
            
            results.append({
                "Stage": stage_name,
                "Timeframe": timeframe,
                "Mode": mode,
                "Strategy": strategy_name,
                "Target": metric_type,
                "Score": formatted_score,
                "Trades": total_trades
            })
        except Exception as e:
            print(f"Failed to parse {path}: {e}")
            
    if not results:
        print("No valid results found to generate leaderboard.")
        return
        
    df = pd.DataFrame(results)
    
    # Disable scientific notation globally for this pandas session just in case
    pd.set_option('display.float_format', lambda x: '%.6f' % x)
    
    markdown_output = "# 🏆 Quant Engine: Absolute Returns Leaderboard\n\n"
    markdown_output += "This leaderboard is automatically generated by recursively scanning the `reports/` directory.\n\n"
    
    # Group by Stage and Timeframe
    for stage in sorted(df['Stage'].unique()):
        markdown_output += f"## {stage}\n"
        stage_df = df[df['Stage'] == stage]
        
        for tf in sorted(stage_df['Timeframe'].unique(), key=lambda x: (len(x), x)): # Sort 1m, 15m, 1h
            markdown_output += f"### Timeframe: {tf}\n"
            tf_df = stage_df[stage_df['Timeframe'] == tf].copy()
            tf_df.sort_values(by=["Mode", "Score"], ascending=[True, False], inplace=True)
            tf_df.drop(columns=['Stage', 'Timeframe'], inplace=True)
            tf_df.reset_index(drop=True, inplace=True)
            
            markdown_output += tf_df.to_markdown(index=False) + "\n\n"
    
    leaderboard_file = os.path.join(base_dir, "LEADERBOARD.md")
    with open(leaderboard_file, "w", encoding="utf-8") as f:
        f.write(markdown_output)
        
    print(f"Successfully generated LEADERBOARD.md ranking {len(df)} strategies!")

if __name__ == "__main__":
    generate_leaderboard()